/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TradeStats;

import org.junit.Test;

public class ProducerTest {
    @Test public void testAppHasAGreeting() {
        Producer classUnderTest = new Producer();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
